### PR TITLE
Update VCDCluster Schema

### PR DESCRIPTION
**Pull request by erkanerol**
Towards https://github.com/giantswarm/giantswarm/issues/24320

This PR reflects the api changes here https://github.com/vmware/cluster-api-provider-cloud-director/commit/2ce0652ae20b993f1c87b484c86f870524345970#diff-5544c3f3769dc4017e4a810b2f349cf3bbf10987c0ec014a6c31103784a6f33dR94

## Checklist

- [x] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Review by kubasobon — APPROVED** [review]

**Comment by erkanerol** [comment]
@vxav This PR solves `vipSubnet` issue because of `LoadBalancer` -> `LoadBalancerConfigSpec` change. However, there is another change regarding `clusterid`. 

```
global:
  vcdConfig:
    clusterid: <HERE_IS_NOT_OK>
    vipSubnet: <HERE_IS_OK>
```

We are filling `clusterid` with `vcdCluster.Spec.RDEId` but it is empty in my new cluster created with 0.2.4

**Comment by erkanerol** [comment]
I added `vcdCluster.Spec.RDEId` -> `vcdCluster.Status.InfraId` change into this PR.

**Comment by vxav** [comment]
Weird, I see it's still in the CRD. I supposed it's good to take from the status field. I don't have the energy to dig through the commits upstream to find if it's changed.

**Review by vxav — APPROVED** [review]
LGTM

**Pull request merged**
