### PR TITLE
generate cluster-values secret for all providers

### PR DESCRIPTION
**Pull request by bavarianbidi**
I can't see a valid reason why we shouldn't create the `cluster-values` secret for all clusters.
In a bad case, the secret might be empty but as we merge the `secret` and the `configmap` into the values, this shouldn't be a problem.

## Checklist

- [x] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Review by calvix — APPROVED** [review]

**Comment by fiunchinho** [comment]
The new secret change has broke cluster creation on GCP. We need this fix asap

```
k --context gs-gunther get apps -n org-giantswarm t03535911-chart-operator -o yaml                                                                                                                                                             

apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  annotations:
    chart-operator.giantswarm.io/force-helm-upgrade: "false"
  creationTimestamp: "2022-11-18T08:32:46Z"
  finalizers:
  - operatorkit.giantswarm.io/app-operator-app
  generation: 1
  labels:
    app-operator.giantswarm.io/version: 6.4.1
    app.kubernetes.io/name: chart-operator
    giantswarm.io/cluster: t03535911
    giantswarm.io/managed-by: cluster-apps-operator
  name: t03535911-chart-operator
  namespace: org-giantswarm
  resourceVersion: "75140943"
  uid: 39dd8992-d814-4142-8fda-b653ebc827f3
spec:
  catalog: default
  config:
    configMap:
      name: t03535911-cluster-values
      namespace: org-giantswarm
    secret:
      name: t03535911-cluster-values
      namespace: org-giantswarm
  install: {}
  kubeConfig:
    context:
      name: t03535911-kubeconfig
    inCluster: false
    secret:
      name: t03535911-kubeconfig
      namespace: org-giantswarm
  name: chart-operator
  namespace: giantswarm
  namespaceConfig: {}
  rollback: {}
  uninstall: {}
  upgrade: {}
  userConfig:
    configMap:
      name: ""
      namespace: ""
    secret:
      name: ""
      namespace: ""
  version: 2.33.0
status:
  appVersion: ""
  release:
    lastDeployed: null
    reason: 'validation error: secret `t03535911-cluster-values` in namespace `org-giantswarm`
      not found'
    status: resource-not-found
  version: ""
```

**Comment by erkanerol** [comment]
Are you sure that this is going to work for vintage? Have you ever checked?

**Comment by bavarianbidi** [comment]
> Are you sure that this is going to work for vintage? Have you ever checked?

Few `vintage` installations doesn't have `cluster-apps-operator` deployed.
And on some others (e.g. `viking`) `cluster-operator` and `cluster-apps-operator` are running. But `cluster-apps-operator` is doing nothing and the cluster-specific `configmap/secret` got created by `cluster-operator`.

**Comment by bavarianbidi** [comment]
@fiunchinho i'm really interested why the "new change" (whatever the new change was) has broke clusters creation on `GCP`. And how this PR fixed the issue. I didn't get it :sweat_smile:

**Comment by fiunchinho** [comment]
The cluster `App` was failing due to missing secret

```
k --context gs-gunther get apps -n org-giantswarm t03535911-chart-operator -o yaml                                                                                                                                                             

apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  annotations:
    chart-operator.giantswarm.io/force-helm-upgrade: "false"
  creationTimestamp: "2022-11-18T08:32:46Z"
  finalizers:
  - operatorkit.giantswarm.io/app-operator-app
  generation: 1
  labels:
    app-operator.giantswarm.io/version: 6.4.1
    app.kubernetes.io/name: chart-operator
    giantswarm.io/cluster: t03535911
    giantswarm.io/managed-by: cluster-apps-operator
  name: t03535911-chart-operator
  namespace: org-giantswarm
  resourceVersion: "75140943"
  uid: 39dd8992-d814-4142-8fda-b653ebc827f3
spec:
  catalog: default
  config:
    configMap:
      name: t03535911-cluster-values
      namespace: org-giantswarm
    secret:
      name: t03535911-cluster-values
      namespace: org-giantswarm
  install: {}
  kubeConfig:
    context:
      name: t03535911-kubeconfig
    inCluster: false
    secret:
      name: t03535911-kubeconfig
      namespace: org-giantswarm
  name: chart-operator
  namespace: giantswarm
  namespaceConfig: {}
  rollback: {}
  uninstall: {}
  upgrade: {}
  userConfig:
    configMap:
      name: ""
      namespace: ""
    secret:
      name: ""
      namespace: ""
  version: 2.33.0
status:
  appVersion: ""
  release:
    lastDeployed: null
    reason: 'validation error: secret `t03535911-cluster-values` in namespace `org-giantswarm`
      not found'
    status: resource-not-found
  version: ""
```

**Pull request merged**
